
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConsultationForm from "@/components/ConsultationForm";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sabza-Franchise ",
  description: "Generated by Sabza",
  icons: {
    icon: "/logo.png", 
  },
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
         {/* Floating Consultation Form - will be visible on all pages */}
        <ConsultationForm />
      </body>
    </html>
  );
}
